docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Usage: usage.md
site_name: laminas-xml2json
site_description: Laminas\Xml2Json
repo_url: 'https://github.com/laminas/laminas-xml2json'
